# fly.toml file generated for thready on 2023-04-18T19:58:34-07:00

app = "thready"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lax"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
